In [1]:
import pandas as pd

In [2]:
drug7 = pd.read_csv('drug7.csv')
drug8 = pd.read_csv('drug8.csv')
d1 = pd.read_csv('disease1.csv')

In [3]:
drug8

             patid  VXX_dt  sup_dt  index GDR_CD  yrdob
0       1073741972     733     737      8      F   1954
1       1073745187    1347    1353      8      M   1952
2       1073745617    1060    1064      8      F   1972
3       1073746413    1457    1459      8      F   1973
4       1073747333    1796    1805      8      F   1981
5       1073747333    1878    1887      8      F   1981
6       1073747333    1932    1961      8      F   1981
7       1073747333    1978    2007      8      F   1981
8       1073747333    2007    2036      8      F   1981
9       1073747333    2143    2202      8      F   1981
10      1073751734    2666    2673      8      M   1923
11      1073753720    1354    1358      8      M   1975
12      1073753873     596     625      8      M   1982
13      1073755449    1234    1234      8      M   1954
14      1073755808    1228    1231      8      M   1982
15      1073755808    1315    1318      8      M   1982
16      1073757139    2349    2353      8      F   1950
17      1073757139    2376    2380      8      F   1950
18      1073760879    2180    2192      8      F   1972
19      1073761133     373     402      8      F   1956
20      1073761133     405     434      8      F   1956
21      1073761133     459     488      8      F   1956
22      1073761674     608     608      8      M   1954
23      1073762105    1371    1373      8      M   1979
24      1073763687    1692    1693      8      M   1973
25      1073766196     891     894      8      F   1949
26      1073767590    1937    1939      8      M   1948
27      1073767843     641     645      8      F   1948
28      1073771062    1627    1628      8      F   1985
29      1073774309     464     473      8      F   1949
...            ...     ...     ...    ...    ...    ...
599990  1610511410    2516    2525      8      M   1972
599991  1610511410    2631    2640      8      M   1972
599992  1610519382    2494    2503      8      F   1960
599993  1610524649    2433    2440      8      F   1943
599994  1610535881    2454    2465      8      M   1953
599995  1610535881    2467    2479      8      M   1953
599996  1610560634    2589    2618      8      F   1957
599997  1610560634    2627    2656      8      F   1957
599998  1610564180    2454    2458      8      M   1969
599999  1610567525    2454    2456      8      F   1945
600000  1610568950    2315    2334      8      F   1979
600001  1610569874    2472    2474      8      F   1982
600002  1610570541    2216    2245      8      F   1961
600003  1610570541    2244    2273      8      F   1961
600004  1610570541    2355    2384      8      F   1961
600005  1610570541    2369    2383      8      F   1961
600006  1610571885    2617    2620      8      F   1946
600007  1610573643    2511    2511      8      M   1963
600008  1610575045    2567    2568      8      F   1977
600009  1610591459    2545    2549      8      M   1952
600010  1610593386    2483    2489      8      F   1970
600011  1610593386    2503    2507      8      F   1970
600012  1610593386    2508    2510      8      F   1970
600013  1610593386    2663    2682      8      F   1970
600014  1610593386    2716    2735      8      F   1970
600015  1610594118    2517    2523      8      F   1981
600016  1610603173    2396    2398      8      M   1974
600017  1610603173    2401    2407      8      M   1974
600018  1610607314    2461    2470      8      F   1961
600019  1610607314    2690    2696      8      F   1961

[600020 rows x 6 columns]

In [9]:
last_date = max(d1['lst_dt'])

In [10]:
d1 = d1.drop_duplicates('patid', keep='first')
drug7_no_drug8 = drug7.loc[~drug7['patid'].isin(drug8['patid'])]

In [12]:
d1 = d1[d1['fst_dt']>=60]
drug8 = drug8[drug8['VXX_dt']<=last_date-60]

In [13]:
drug8_d1_merge = pd.merge(drug8, d1, left_on = 'patid', right_on = 'patid', how = 'left')

In [14]:
drug8_d1 = drug8_d1_merge[(drug8_d1_merge['fst_dt']> drug8_d1_merge['VXX_dt']+14) & (drug8_d1_merge['fst_dt']< drug8_d1_merge['VXX_dt']+60)]
drug8_no_d1 = drug8_d1_merge[(drug8_d1_merge['fst_dt']> drug8_d1_merge['VXX_dt']+60)|drug8_d1_merge['fst_dt'].isna()]
drug8_no_d1 = drug8_no_d1[~drug8_no_d1['patid'].isin(drug8_d1['patid'])]

In [15]:
drug7_d1 = drug7_no_drug8[drug7_no_drug8['patid'].isin(d1['patid'])]
drug7_no_d1 = drug7_no_drug8[~drug7_no_drug8['patid'].isin(d1['patid'])]

In [26]:
len(drug7_d1.drop_duplicates('patid')),len(drug7_no_d1.drop_duplicates('patid')),len(drug8_d1.drop_duplicates('patid')),len(drug8_no_d1.drop_duplicates('patid'))

(4636, 565817, 104, 232766)

In [28]:
4636/565817

0.008193461843670303

In [29]:
104/ 232766

0.0004468006495794059

In [27]:
import numpy as np
from scipy.stats import chi2_contingency

d = np.array([[4636, 565817], [104, 232766]])
chi2_contingency(d)

(1661.6385656009952, 0.0, 1, array([[  3365.95269898, 567087.04730102],
        [  1374.04730102, 231495.95269898]]))

In [33]:
tmp = drug7_d1.drop_duplicates('patid')
print(len(tmp[tmp['GDR_CD']=='M']))
tmp = drug7_no_d1.drop_duplicates('patid')
print(len(tmp[tmp['GDR_CD']=='M']))
tmp = drug8_d1.drop_duplicates('patid')
print(len(tmp[tmp['GDR_CD_x']=='M']))
tmp = drug8_no_d1.drop_duplicates('patid')
print(len(tmp[tmp['GDR_CD_x']=='M']))

1152
180308
31
77533

In [34]:
1152/180308, 31/77533

(0.006389067595447789, 0.0003998297499129403)

create new column (before the first day, whether patient taking drugX)

1. matching how many pair we have after the match
2. propensity score 

180 days

for control group
never take drug 8

as long as have one disease, use the record(go back rand(14,60) days). 
otherwise, pick a time randomly in the middle, calculate all the covariance at the time.

among the date taking the durg 8. if have disease 1, pick the first date of taking drug 8. if no disease 1, pick a random record

date before the date and the most recent condition date

disease 1 2 5
drug 10 3 8